### ISSUE TITLE
Android support for styling

### ISSUE THREAD

**Issue by i-tu** [JeanLebrument/react-native-fabric-digits#31]
Hi, thanks for making react-native-fabric-digits! It's a solid piece of software.

The options prop field "appearance" works on iOS but does not seem to work on Android. Can you confirm whether this is supported, or I'm running into some bug? Is there some alternative way to get styling to work on Android?

Best regards,
Ian

**Comment by JeanLebrument** [comment]
Hello Ian,

I didn't participate to the Android development, I would rather let Android developers responds to your question.

Best,

Jean

Jean Lebrument

On Fri, Aug 05, 2016 at 11:15 AM Ian Tuomi

<
mailto:Ian Tuomi notifications@github.com

> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Hi, thanks for making react-native-fabric-digits! It's a solid piece of software.

The options prop field "appearance" works on iOS but does not seem to work on Android. Can you confirm whether this is supported, or I'm running into some bug? Is there some alternative way to get styling to work on Android?

Best regards,

Ian

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/JeanLebrument/react-native-fabric-digits/issues/31
, or

**Comment by dhrrgn** [comment]
This is actually already supported.  On Android, you have to add the a Custom Digits Theme to your `styles` resource file.  I have created a pull request to add these instructions to the README here: https://github.com/JeanLebrument/react-native-fabric-digits/pull/35 

/cc @JeanLebrument

**Comment by i-tu** [comment]
Thank you Dan! The added documentation is very useful :)
